#!/bin/bash

#Pull wtf-exercise repo onto nodes

for node in 0 1 2
	do ctool run death_star $node 'git clone https://github.com/sequoyha/wtf-exercise.git'
done

ctool run yavin_4 0 'git clone https://github.com/sequoyha/wtf-exercise.git'
ctool run alderaan 0 'git clone https://github.com/sequoyha/wtf-exercise.git'

#CONFIGURE CLUSTERS
echo "Setting up Multi-instance on alderaan cluster"
ctool run alderaan 0 'wtf-exercise/config/configure_dense_nodes' 
echo "Setting up Multi-instance on yavin_4 cluster"
ctool run yavin_4 0 'wtf-exercise/config/configure_dense_nodes'
echo "sleeping 30 seconds to allow configuration changes to take effect"
sleep 30

#RESTART DSE ON CLUSTERS
echo "Starting DSE and additional nodes on alderaan cluster"
ctool restart alderaan 0
echo "Sleeping 60 seconds to allow restart to complete"
sleep 60
echo "Starting dse-alderaan_1"
ctool run alderaan 0 'sudo service dse-alderaan_1 start'
echo "Sleeping 5 minutes to allow dse-alderaan_1 to bootstrap fully"
sleep 300
echo "Starting dse-alderaan_2"
ctool run alderaan 0 'sudo service dse-alderaan_2 start'
echo "Sleeping 5 minutes to allow dse-alderaan_2 to bootstrap fully"
sleep 300
echo "Verifying all nodes in alderaan cluster are up and normal"
ctool run alderaan 0 'nodetool status'

echo "Starting DSE and additional nodes on yavin_4 cluster"
ctool restart yavin_4 0
echo "Sleeping 60 seconds to allow restart to complete"
sleep 60
echo "Starting dse-yavin_4_1"
ctool run yavin_4 0 'sudo service dse-yavin_4_1 start'
echo "Sleeping 5 minutes to allow dse-yavin_4_1 to bootstrap fully"
sleep 300
echo "Starting dse-yavin_4_2"
ctool run yavin_4 0 'sudo service dse-yavin_4_2 start'
echo "Sleeping 5 minutes to allow dse-yavin_4_2 to bootstrap fully"
sleep 300
echo "Verifying all nodes in yavin_4 cluster are up and normal"
ctool run yavin_4 0 'nodetool status'

#SET UP ADVANCED REPLICATION
echo "Gathering death_star IP addresses for Advanced Replication configuration"
for num in 0 1 2
	do DEATH_STAR_ADDRESS=`ctool info death_star | grep -A2 "Node ${num}:" | grep "public ip:" | cut -d : -f2 | sed -e 's/^[ \t]*//'`,$DEATH_STAR_ADDRESS
done
DEATH_STAR_ADDRESS=$DEATH_STAR_ADDRESS`ctool info death_star | grep -A2 "Node 3:" | grep "public ip:" | cut -d : -f2 | sed -e 's/^[ \t]*//'`
echo $DEATH_STAR_ADDRESS >> hub_addresses_for_advanced_replication
echo "Sending IP addresses for death_star cluster to yavin_4 and alderaan"
ctool scp yavin_4 0 hub_addresses_for_advanced_replication /home/automaton
ctool scp alderaan 0 hub_addresses_for_advanced_replication /home/automaton

#SCHEMA and DATA
echo "Beginning schema work on death_star"
ctool run death_star 0 'wtf-exercise/config/configure_schema' &
echo "Beginning schema work on yavin_4"
ctool run yavin_4 0 'wtf-exercise/config/configure_schema' &
echo "Beginning schema work on alderaan"
ctool run alderaan 0 'wtf-exercise/config/configure_schema' &
date
echo "Sleeping for 3 hours for initial data population"
sleep 10800
#UMMMM
for node in 0 2
	do ctool run death_star $node 'sudo ~/wtf-exercise/config/Tiered_star'
	ctool restart death_star $node
done
ctool run death_star 1 'sudo ~/wtf-exercise/config/Tiered_death'
ctool restart death_star 1 &

for node in 0 1 2
	do ctool run death_star $node 'sudo rm -rf ~/wtf-exercise'
done
ctool run yavin_4 0 'sudo rm -rf ~/wtf-exercise'
ctool run alderaan 0 'sudo rm -rf ~/wtf-exercise'
echo "what_have_you_done script completed. Help!!!!"
