#!/bin/bash

#LAUNCH CLUSTER
echo "Creating clusters for WTF project"
echo "Launching death_star cluster of 3 nodes"
ctool launch death_star --ttl 7200 3 "ec2:us-east-1:3" &
sleep 15
echo "Launching alderaan cluster of 1 node"
ctool launch -i c3.8xlarge --ttl 7200 alderaan 1 "ec2:us-east-1:1" &
sleep 15
echo "Launching yavin_4 cluster of 1 node"
ctool launch -i c3.8xlarge --ttl 7200 yavin_4 1 "ec2:us-east-1:1" &
sleep 15
echo "Launching opscenter_6 cluster of 1 node"
ctool launch --ttl 7200 opscenter_6 1 "ec2:us-east-1:1" &
wait
echo "All clusters launched"

#INSTALL DSE
# Use OpsCenter LCM to configure and Install DSE 5.0 on all servers

#START DSE
# Use OpsCenter LCM to start  DSE 5.0 on all servers
